### ISSUE TITLE
Index the date as a timestamp and display it nicely

### ISSUE THREAD

**Issue by seafoox** [algolia/wordpress-search#3]
Don't you think we should index the created / update dates as timestamps, so we could easily display them them in a nice way using plugins like http://momentjs.com/
We could even display 3 months ago, ....

For now the date display looks a bit complicated
![image](https://cloud.githubusercontent.com/assets/1101220/8143419/8d88eb64-11ab-11e5-8f21-650124ac4fec.png)

What do you think?

**Comment by redox** [comment]
Yes yes, part of the plan.
